-- 1. Alter finance_entries to support Petty Cash Allocations
-- This flag indicates that this expense entry is actually a 'deposit' into the Petty Cash fund
ALTER TABLE finance_entries ADD COLUMN is_petty_cash boolean DEFAULT false;

-- 2. Create table for Petty Cash Expenses (Spending from the fund)
CREATE TABLE IF NOT EXISTS petty_cash_entries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id), -- Who entered this
    admin_id uuid, -- Organization owner (for filtering)
    description text not null,
    amount numeric not null, -- How much was spent
    date date not null default CURRENT_DATE,
    receipt_url text, -- Optional image
    category text -- e.g., Food, Travel, Office Supplies
);

-- 3. Enable RLS
ALTER TABLE petty_cash_entries ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Admin can do everything
CREATE POLICY "Admins can view all petty cash" ON petty_cash_entries FOR SELECT 
USING (auth.uid() = admin_id OR auth.uid()::text = admin_id::text); -- Cast for safety if UUID handling varies

CREATE POLICY "Admins can insert petty cash" ON petty_cash_entries FOR INSERT 
WITH CHECK (auth.uid() = admin_id OR auth.uid()::text = admin_id::text);

CREATE POLICY "Admins can delete petty cash" ON petty_cash_entries FOR DELETE 
USING (auth.uid() = admin_id OR auth.uid()::text = admin_id::text);

-- Employees can View and Insert (Spend), but maybe not Delete (Audit trail)
-- We need to check if auth.uid() is an employee of admin_id
-- For simplicity in this simplified RLS model:
CREATE POLICY "Employees can view their org's petty cash" ON petty_cash_entries FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND admin_id = petty_cash_entries.admin_id
    )
);

CREATE POLICY "Employees can add petty cash entries" ON petty_cash_entries FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND admin_id = petty_cash_entries.admin_id
    )
);

-- Grant permissions
GRANT ALL ON petty_cash_entries TO authenticated;
GRANT ALL ON petty_cash_entries TO service_role;
