-- Create a standalone Petty Cash table
CREATE TABLE IF NOT EXISTS petty_cash_entries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id),
    admin_id uuid, -- Organization owner (for filtering)
    description text not null,
    amount numeric not null,
    transaction_type text not null check (transaction_type in ('add_fund', 'expense')),
    date date not null default CURRENT_DATE,
    receipt_url text,
    category text -- e.g., Food, Travel, Office Supplies
);

-- Enable RLS
ALTER TABLE petty_cash_entries ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow Read for authenticated users (Admin and Employee)
DROP POLICY IF EXISTS "Users can view petty_cash_entries" ON petty_cash_entries;
CREATE POLICY "Users can view petty_cash_entries" ON petty_cash_entries FOR SELECT 
USING (
    (select auth.role()) = 'authenticated'
);

-- Allow Insert for authenticated users (Admin and Employee)
DROP POLICY IF EXISTS "Users can insert petty_cash_entries" ON petty_cash_entries;
CREATE POLICY "Users can insert petty_cash_entries" ON petty_cash_entries FOR INSERT 
WITH CHECK (
    (select auth.role()) = 'authenticated'
);

-- Allow Delete for Admins only (or creator)
DROP POLICY IF EXISTS "Admins can delete petty_cash_entries" ON petty_cash_entries;
CREATE POLICY "Admins can delete petty_cash_entries" ON petty_cash_entries FOR DELETE 
USING (
    ((select auth.uid()) = admin_id OR (select auth.uid())::text = admin_id::text)
    OR
    (user_id = (select auth.uid()))
);

-- Grant permissions to authenticated users to ensure they can access the table
GRANT ALL ON petty_cash_entries TO authenticated;
GRANT ALL ON petty_cash_entries TO service_role;
